version: '3.8'

services:
  app:
    image: cesaramoranbb/flask:v1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: prueba
    ports:
      - "5000:5000"